name: feely
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fpdart: ^1.1.1
  gap: ^3.0.1
  dio: ^5.7.0
  talker_dio_logger: ^4.5.5
  connectivity_plus: ^6.1.1
  path_provider: ^2.1.5
  path: ^1.9.0
  auto_route: ^10.1.0+1
  flutter_svg: ^2.0.16
  fluentui_system_icons: ^1.1.270
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  flutter_animate: ^4.5.2
  flutter_gen: ^5.8.0
  hugeicons: ^0.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.2.3
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/svg/illustrations/


  fonts:
   - family: SF Pro
     fonts:
       - asset: assets/fonts/SF-Pro-Rounded-Black.otf
         weight: 900
       - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
         weight: 800
       - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
         weight: 700
       - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
         weight: 600
       - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
         weight: 500
       - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
         weight: 400
       - asset: assets/fonts/SF-Pro-Rounded-Light.otf
         weight: 300
       - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf
         weight: 200
       - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
         weight: 100
